version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/base:current
    steps:
      - run: ssh -oStrictHostKeyChecking=no -v $USER@$DNS "./deploy.sh"

workflows:
  deploy-to-ec2:
    jobs:
      - deploy